title:             Thoughts v_strochku
email:             damir@mukimov.com
description:       Personal blog with some useful notes about sowtware development, photogrpahy, videography and etc.
author:            Damir Mukimov
baseurl:           "/"
url:               "http://samyrai.github.io"
timezone:          Europe/Berlin
education_in_main: false

# Social Profiles
instagram_username:  v_strochku
github_username:   samyrai
# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
